spring:
  profiles:
    active: dev
    
    
---
server:
  port: 4001
spring:
  profiles: prod
  application:
    name: microservice-config-prod
    
    
---
server:
  port: 4002
spring:
  profiles: dev
  application:
    name: microservice-config-dev
    
    
---
server:
  port: 4003
spring:
  profiles: test
  application:
    name: microservice-config-test
